server:
  port: 9090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/document_explainer
    username: root
    password: ab12+-34
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  ai:
    openai:
      api-key: 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

files:
  documents: documents/

