server:
  port: 9090

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/document_explainer
    username: user
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  ai:
    openai:
      api-key: sk-9B4y9XK1mK2lQ4oE2pT3oF6oB7oR8oA1

files:
  documents: documents/

