server:
  port: 9090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/document_explainer
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  ai:
    openai:

files:
  documents: documents/

