server:
  port: 9090

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/document_explainer
    username: user
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true



files:
  documents: documents/

