name: Document Explainer Pipeline

env:
  SPRING_PROFILES_ACTIVE: test
  TEST_DB_URL: jdbc:mysql://localhost:3307/document_explainer
  TEST_DB_USERNAME: user
  TEST_DB_PASSWORD: root

on:
  push:       { branches: ["master"] }
  pull_request: { branches: ["master"] }

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        ports:
          # hostPort : containerPort
          - 3307:3306            # 👈 maps 3306 inside the container to 3307 on the runner
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_USER: user
          MYSQL_PASSWORD: root
          MYSQL_DATABASE: document_explainer
        options: >-
          --health-cmd="mysqladmin ping -h localhost --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Wait for MySQL :3307
        run: |
          until mysqladmin ping -h "127.0.0.1" -P 3307 -u root -proot --silent; do
            echo "Waiting for MySQL on port 3307..."
            sleep 2
          done

      - name: Build with Maven
        run: mvn clean install

      - name: Build & push Docker image
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: adityazaware/document_explainer
          tags: latest
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
